### ISSUE TITLE
Can't work on Flarum 1.3.1

### ISSUE THREAD

**Issue by imshuzai** [flagrow/mason#33]
## Bug Report

**Current Behavior**
Composer works weirdly after updated to 1.3.1 and enabled Mason. Mason field not displaying in discussions.

**Steps to Reproduce**
1. Install Flarum 1.3.1.
2. Install FoF Mason.
3. Enable Mason.
4. Click Start a Discussion button.

**Expected Behavior**
Composer works properly and Mason field is displayed in discussions.

**Screenshots**

![](https://tu.eebk.com/item/62a5a5b70947543129160252.gif)

For convenience, I recorded this GIF on freeflarum. I got _same_ errors on my self-hosted Flarum.

**Environment**
- Flarum version: 1.3.1
- Extension version: 1.0.1
- Website URL: http://example.com
- Webserver: [nginx]
- Hosting environment: [vps]
- PHP version: 7.4.20
- Browser: [chrome 102.0.5005.115]

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Possible solution(s)**

**Additional Context**
Errors in console after clicked Start a Discussion button:
```
forum.js?v=115bc3d5:sourcemap:2 TypeError: t.suggested_answers(...).forEach is not a function
at forum.js?v=115bc3d5:sourcemap:383:11233
at Array.forEach (<anonymous>)
at n.oninit (forum.js?v=115bc3d5:sourcemap:383:11190)
at Function.a (forum.js?v=115bc3d5:sourcemap:2:145019)
at j (forum.js?v=115bc3d5:sourcemap:2:156895)
at forum.js?v=115bc3d5:sourcemap:2:146713
at forum.js?v=115bc3d5:sourcemap:2:146916
at c (forum.js?v=115bc3d5:sourcemap:2:147039)
at l (forum.js?v=115bc3d5:sourcemap:2:145183)
at forum.js?v=115bc3d5:sourcemap:2:146031
a @ forum.js?v=115bc3d5:sourcemap:2
e.show @ forum.js?v=115bc3d5:sourcemap:2
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
n.newDiscussionAction @ forum.js?v=115bc3d5:sourcemap:2
onclick @ forum.js?v=115bc3d5:sourcemap:2
L.handleEvent @ forum.js?v=115bc3d5:sourcemap:2
forum.js?v=115bc3d5:sourcemap:2 TypeError: Cannot read properties of undefined (reading 'onbeforeupdate')
at forum.js?v=115bc3d5:sourcemap:2:149948
at p (forum.js?v=115bc3d5:sourcemap:2:150156)
at f (forum.js?v=115bc3d5:sourcemap:2:149572)
at forum.js?v=115bc3d5:sourcemap:2:151356
at p (forum.js?v=115bc3d5:sourcemap:2:151394)
at f (forum.js?v=115bc3d5:sourcemap:2:148072)
at forum.js?v=115bc3d5:sourcemap:2:151356
at p (forum.js?v=115bc3d5:sourcemap:2:151394)
at f (forum.js?v=115bc3d5:sourcemap:2:149572)
at forum.js?v=115bc3d5:sourcemap:2:151356
a @ forum.js?v=115bc3d5:sourcemap:2
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
requestAnimationFrame (async)
u @ forum.js?v=115bc3d5:sourcemap:2
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
dispatch @ forum.js?v=115bc3d5:sourcemap:2
v.handle @ forum.js?v=115bc3d5:sourcemap:2
trigger @ forum.js?v=115bc3d5:sourcemap:2
simulate @ forum.js?v=115bc3d5:sourcemap:2
n @ forum.js?v=115bc3d5:sourcemap:2
handler @ forum.js?v=115bc3d5:sourcemap:2
dispatch @ forum.js?v=115bc3d5:sourcemap:2
v.handle @ forum.js?v=115bc3d5:sourcemap:2
trigger @ forum.js?v=115bc3d5:sourcemap:2
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
each @ forum.js?v=115bc3d5:sourcemap:2
each @ forum.js?v=115bc3d5:sourcemap:2
trigger @ forum.js?v=115bc3d5:sourcemap:2
C.each.C.fn.<computed> @ forum.js?v=115bc3d5:sourcemap:2
n.focus @ forum.js?v=115bc3d5:sourcemap:2
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
l @ forum.js?v=115bc3d5:sourcemap:2
c @ forum.js?v=115bc3d5:sourcemap:2
setTimeout (async)
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
u @ forum.js?v=115bc3d5:sourcemap:2
fireWith @ forum.js?v=115bc3d5:sourcemap:2
fire @ forum.js?v=115bc3d5:sourcemap:2
u @ forum.js?v=115bc3d5:sourcemap:2
fireWith @ forum.js?v=115bc3d5:sourcemap:2
a @ forum.js?v=115bc3d5:sourcemap:2
u @ forum.js?v=115bc3d5:sourcemap:2
fireWith @ forum.js?v=115bc3d5:sourcemap:2
fire @ forum.js?v=115bc3d5:sourcemap:2
dequeue @ forum.js?v=115bc3d5:sourcemap:2
r.complete @ forum.js?v=115bc3d5:sourcemap:2
u @ forum.js?v=115bc3d5:sourcemap:2
fireWith @ forum.js?v=115bc3d5:sourcemap:2
u @ forum.js?v=115bc3d5:sourcemap:2
C.fx.tick @ forum.js?v=115bc3d5:sourcemap:2
ue @ forum.js?v=115bc3d5:sourcemap:2
requestAnimationFrame (async)
ue @ forum.js?v=115bc3d5:sourcemap:2
requestAnimationFrame (async)
ue @ forum.js?v=115bc3d5:sourcemap:2
requestAnimationFrame (async)
ue @ forum.js?v=115bc3d5:sourcemap:2
requestAnimationFrame (async)
ue @ forum.js?v=115bc3d5:sourcemap:2
requestAnimationFrame (async)
ue @ forum.js?v=115bc3d5:sourcemap:2
requestAnimationFrame (async)
ue @ forum.js?v=115bc3d5:sourcemap:2
C.fx.start @ forum.js?v=115bc3d5:sourcemap:2
C.fx.timer @ forum.js?v=115bc3d5:sourcemap:2
he @ forum.js?v=115bc3d5:sourcemap:2
s @ forum.js?v=115bc3d5:sourcemap:2
dequeue @ forum.js?v=115bc3d5:sourcemap:2
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
each @ forum.js?v=115bc3d5:sourcemap:2
each @ forum.js?v=115bc3d5:sourcemap:2
queue @ forum.js?v=115bc3d5:sourcemap:2
animate @ forum.js?v=115bc3d5:sourcemap:2
n.animateHeightChange @ forum.js?v=115bc3d5:sourcemap:2
n.show @ forum.js?v=115bc3d5:sourcemap:2
n.animatePositionChange @ forum.js?v=115bc3d5:sourcemap:2
n.onupdate @ forum.js?v=115bc3d5:sourcemap:2
a @ forum.js?v=115bc3d5:sourcemap:2
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
a @ forum.js?v=115bc3d5:sourcemap:2
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
requestAnimationFrame (async)
u @ forum.js?v=115bc3d5:sourcemap:2
L.handleEvent @ forum.js?v=115bc3d5:sourcemap:2
forum.js?v=115bc3d5:sourcemap:2 TypeError: Cannot read properties of undefined (reading 'onbeforeupdate')
at forum.js?v=115bc3d5:sourcemap:2:149948
at p (forum.js?v=115bc3d5:sourcemap:2:150156)
at f (forum.js?v=115bc3d5:sourcemap:2:149572)
at forum.js?v=115bc3d5:sourcemap:2:151356
at p (forum.js?v=115bc3d5:sourcemap:2:151394)
at f (forum.js?v=115bc3d5:sourcemap:2:148072)
at forum.js?v=115bc3d5:sourcemap:2:151356
at p (forum.js?v=115bc3d5:sourcemap:2:151394)
at f (forum.js?v=115bc3d5:sourcemap:2:149572)
at forum.js?v=115bc3d5:sourcemap:2:151356
a @ forum.js?v=115bc3d5:sourcemap:2
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
requestAnimationFrame (async)
u @ forum.js?v=115bc3d5:sourcemap:2
(anonymous) @ forum.js?v=115bc3d5:sourcemap:2
dispatch @ forum.js?v=115bc3d5:sourcemap:2
v.handle @ forum.js?v=115bc3d5:sourcemap:2
trigger @ forum.js?v=115bc3d5:sourcemap:2
simulate @ forum.js?v=115bc3d5:sourcemap:2
n @ forum.js?v=115bc3d5:sourcemap:2
```
It will shows more errors if click on buttons on composer.
